version: '3.7'

services:
  # Database
  db:
    image: mysql:8.0.23
    volumes:
     - v_mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MYDB
      MYSQL_USER: testusr
      MYSQL_PASSWORD: password
    expose:
      - '3306'
    ports:
      - '3306:3306'
    networks:
      - mysqlnet
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - '8899:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysqlnet
  # Keycloak
  keycloak:
    depends_on:
      - db
    image: jboss/keycloak:12.0.2
    restart: always
    environment:
        DB_VENDOR: MYSQL
        DB_ADDR: db
        DB_DATABASE: MYDB
        DB_USER: testusr
        DB_PASSWORD: password
        #JDBC_PARAMS: "connectTimeout=30000"
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
    expose:
      - '8443'
      - '8080'
    ports:
      - '8080:8080'
      - '8443:8443'
    networks:
      - mysqlnet
volumes:
  v_mysql_data:
networks:
  mysqlnet:
